### ISSUE TITLE
Keras Utils Has Moved

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-image-classification-with-mlps-lab#1]
## Issue Subtype

- [ ] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

```
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)
```
As well as instructions saying to use the `keras.utils` submodule

### Concern

The `keras` library doesn't have this function available, so this causes an error

## (Optional) Proposed Solution

One suggestion was to replace `keras.utils` with `keras.utils.np_utils`

I believe that this would involve using a non-public API, and instead we should change the Keras import so that it uses the TensorFlow submodule. See [Keras documentation](https://keras.io/api/utils/python_utils/#to_categorical-function)                              

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [x] IllumiDesk

**Comment by jessepisel** [comment]
fixed with [a2fd5cb](https://github.com/learn-co-curriculum/dsc-image-classification-with-mlps-lab/commit/a2fd5cb9e36203417ef0eb88bc586536efdd4e73)
